export const chatRoomList = [
    {
        chatRoomId: 1,
        chatRoomName: "강아지 산책 모임",
        userName: "가가가",
        description: "강아지강아지",
        coverImage: "",
        chatRoomTags: ["강아지", "산책", "반려견"],
    },
    {
        chatRoomId: 2,
        chatRoomName: "말티즈",
        userName: "나나나",
        description: "말티즈를 좋아하는 사람들",
        coverImage: "",
        chatRoomTags: ["강아지", "말티즈", "반려견"],
    },
    {
        chatRoomId: 3,
        chatRoomName: "냥사모",
        userName: "다다다",
        description: "고양이를 사랑하는 모임",
        coverImage: "",
        chatRoomTags: ["고양이"],
    },
    {
        chatRoomId: 4,
        chatRoomName: "메롱",
        userName: "라라라",
        description: "메롱메롱",
        coverImage: "",
        chatRoomTags: ["메롱"],
    },
    {
        chatRoomId: 5,
        chatRoomName: "테스트",
        userName: "테스트",
        description: "테스트 채팅방",
        coverImage: "",
        chatRoomTags: ["테스트1", "테스트2"],
    },
    {
        chatRoomId: 6,
        chatRoomName: "메롱",
        userName: "라라라",
        description: "메롱메롱",
        coverImage: "",
        chatRoomTags: ["메롱"],
    },
    {
        chatRoomId: 7,
        chatRoomName: "테스트",
        userName: "테스트",
        description: "테스트 채팅방",
        coverImage: "",
        chatRoomTags: ["테스트1", "테스트2"],
    },
    {
        chatRoomId: 8,
        chatRoomName: "메롱",
        userName: "라라라",
        description: "메롱메롱",
        coverImage: "",
        chatRoomTags: ["메롱"],
    },
    {
        chatRoomId: 9,
        chatRoomName: "테스트",
        userName: "테스트",
        description: "테스트 채팅방",
        coverImage: "",
        chatRoomTags: ["테스트1", "테스트2"],
    },
];

export const messageList = [
    {
        userId: 1,
        userName: "가가가",
        messageId: 1,
        content: "안녕하세요 여러분!",
        createdAt: "2023-06-08T10:30:00",
    },
    {
        userId: 2,
        userName: "나나나",
        messageId: 2,
        content: "반갑습니다! 말티즈 좋아하시는 분들 계신가요?",
        createdAt: "2023-06-08T10:32:15",
    },
    {
        userId: 3,
        userName: "다다다",
        messageId: 3,
        content: "고양이 사랑하는 모임이라니 저도 참여하고 싶어요!",
        createdAt: "2023-06-08T10:35:30",
    },
    {
        userId: 1,
        userName: "가가가",
        messageId: 4,
        content: "저는 강아지 산책 모임에 관심이 있어요.",
        createdAt: "2023-06-08T10:38:00",
    },
    {
        userId: 4,
        userName: "라라라",
        messageId: 5,
        content: "메롱메롱! 다들 오늘 기분은 어떠신가요?",
        createdAt: "2023-06-08T10:40:10",
    },
    {
        userId: 5,
        userName: "테스트",
        messageId: 6,
        content: "테스트 채팅방에 오신 것을 환영합니다!",
        createdAt: "2023-06-08T10:42:30",
    },
    {
        userId: 2,
        userName: "나나나",
        messageId: 7,
        content: "저희 말티즈 모임에서는 귀여운 말티즈 사진도 공유해요!",
        createdAt: "2023-06-08T10:45:00",
    },
    {
        userId: 3,
        userName: "다다다",
        messageId: 8,
        content: "고양이 사료 추천 좀 해주세요!",
        createdAt: "2023-06-08T10:47:20",
    },
    {
        userId: 1,
        userName: "가가가",
        messageId: 9,
        content: "강아지 산책 모임에서는 어디로 주로 가시나요?",
        createdAt: "2023-06-08T10:50:00",
    },
    {
        userId: 4,
        userName: "라라라",
        messageId: 10,
        content: "오늘 날씨가 정말 좋네요!",
        createdAt: "2023-06-08T10:52:40",
    },
    {
        userId: 5,
        userName: "테스트",
        messageId: 11,
        content: "테스트1과 테스트2 태그를 달아보았어요.",
        createdAt: "2023-06-08T10:55:00",
    },
    {
        userId: 2,
        userName: "나나나",
        messageId: 12,
        content: "말티즈 모임에서 다음 주에 오프라인 모임 어떠신가요?",
        createdAt: "2023-06-08T10:58:30",
    },
    {
        userId: 3,
        userName: "다다다",
        messageId: 13,
        content: "고양이 사진 올려드릴게요!",
        createdAt: "2023-06-08T11:01:00",
    },
    {
        userId: 1,
        userName: "가가가",
        messageId: 14,
        content: "강아지 산책 모임에서 만나뵙고 싶네요!",
        createdAt: "2023-06-08T11:03:20",
    },
    {
        userId: 4,
        userName: "라라라",
        messageId: 15,
        content: "메롱메롱~ 오늘 하루도 힘내세요!",
        createdAt: "2023-06-08T11:06:00",
    },
    {
        userId: 5,
        userName: "테스트",
        messageId: 16,
        content: "테스트 채팅방에서는 자유롭게 대화 나누시면 됩니다!",
        createdAt: "2023-06-08T11:08:30",
    },
    {
        userId: 2,
        userName: "나나나",
        messageId: 17,
        content: "말티즈 털 관리 어떻게 하시나요?",
        createdAt: "2023-06-08T11:11:00",
    },
    {
        userId: 3,
        userName: "다다다",
        messageId: 18,
        content: "고양이 사료 중에 00 브랜드 추천해요!",
        createdAt: "2023-06-08T11:13:20",
    },
    {
        userId: 1,
        userName: "가가가",
        messageId: 19,
        content: "강아지 산책 시 주의사항 공유해주세요!",
        createdAt: "2023-06-08T11:16:00",
    },
    {
        userId: 4,
        userName: "라라라",
        messageId: 20,
        content: "메롱메롱~ 오늘 점심 메뉴는 뭐 드실 예정이신가요?",
        createdAt: "2023-06-08T11:18:30",
    },
    {
        userId: 5,
        userName: "테스트",
        messageId: 21,
        content: "테스트 채팅방에서는 다양한 주제로 대화 나눠보아요!",
        createdAt: "2023-06-08T11:21:00",
    },
    {
        userId: 2,
        userName: "나나나",
        messageId: 22,
        content: "말티즈 분양 정보 아시는 분 있나요?",
        createdAt: "2023-06-08T11:23:20",
    },
    {
        userId: 3,
        userName: "다다다",
        messageId: 23,
        content: "고양이 장난감 추천 부탁드려요!",
        createdAt: "2023-06-08T11:26:00",
    },
    {
        userId: 1,
        userName: "가가가",
        messageId: 24,
        content: "강아지 산책 후 간식으로 뭐 주시나요?",
        createdAt: "2023-06-08T11:28:30",
    },
    {
        userId: 4,
        userName: "라라라",
        messageId: 25,
        content: "메롱메롱~ 오늘 저녁엔 뭐 드실 예정이신가요?",
        createdAt: "2023-06-08T11:31:00",
    },
    {
        userId: 5,
        userName: "테스트",
        messageId: 26,
        content: "테스트1 태그와 관련된 이야기 나눠봐요!",
        createdAt: "2023-06-08T11:33:20",
    },
    {
        userId: 2,
        userName: "나나나",
        messageId: 27,
        content: "말티즈 애견 카페 다녀오신 분 계신가요?",
        createdAt: "2023-06-08T11:36:00",
    },
    {
        userId: 3,
        userName: "다다다",
        messageId: 28,
        content: "고양이 입양 시 주의사항 알려주세요!",
        createdAt: "2023-06-08T11:38:30",
    },
    {
        userId: 1,
        userName: "가가가",
        messageId: 29,
        content: "강아지 산책 시 필수 아이템 추천해주세요!",
        createdAt: "2023-06-08T11:41:00",
    },
    {
        userId: 4,
        userName: "라라라",
        messageId: 30,
        content: "메롱메롱~ 주말 계획은 어떻게 되시나요?",
        createdAt: "2023-06-08T11:43:20",
    },
    {
        userId: 5,
        userName: "테스트",
        messageId: 31,
        content: "테스트2 태그와 관련된 이야기도 나눠봐요!",
        createdAt: "2023-06-08T11:46:00",
    },
    {
        userId: 2,
        userName: "나나나",
        messageId: 32,
        content: "말티즈 모임에서 다음에 어떤 활동하면 좋을까요?",
        createdAt: "2023-06-08T11:48:30",
    },
    {
        userId: 3,
        userName: "다다다",
        messageId: 33,
        content: "고양이 집사님들 모여라!",
        createdAt: "2023-06-08T11:51:00",
    },
    {
        userId: 1,
        userName: "가가가",
        messageId: 34,
        content: "강아지 산책 코스 추천해주세요!",
        createdAt: "2023-06-08T11:53:20",
    },
    {
        userId: 4,
        userName: "라라라",
        messageId: 35,
        content: "메롱메롱~ 좋아하는 음악 장르는 뭔가요?",
        createdAt: "2023-06-08T11:56:00",
    },
    {
        userId: 5,
        userName: "테스트",
        messageId: 36,
        content: "테스트 채팅방에서 재미있는 이벤트 기획해봐요!",
        createdAt: "2023-06-08T11:58:30",
    },
    {
        userId: 2,
        userName: "나나나",
        messageId: 37,
        content: "말티즈 건강 관리 팁 공유해주세요!",
        createdAt: "2023-06-08T12:01:00",
    },
    {
        userId: 3,
        userName: "다다다",
        messageId: 38,
        content: "고양이 간식으로 뭐가 좋을까요?",
        createdAt: "2023-06-08T12:03:20",
    },
    {
        userId: 1,
        userName: "가가가",
        messageId: 39,
        content: "강아지 산책 후 목욕 꼭 시켜주시나요?",
        createdAt: "2023-06-08T12:06:00",
    },
    {
        userId: 4,
        userName: "라라라",
        messageId: 40,
        content: "메롱메롱~ 다들 즐거운 하루 보내세요!",
        createdAt: "2023-06-08T12:08:30",
    },
];